package blog.anirbanm.xml.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 24 10:13:09 IST 2018
// ---------------------------------------------------------------------
public interface XmlDemoAM extends ApplicationModule {
    void printXml(String type);
}

